version: '3.8'

services:
  web:
    build: ./services/web
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./services/web/:/app
      - static_volume:/home/app/web/project/static
    ports:
      - "5001:5000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
    
  db:
    image: postgres:15.3-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=chatlite_dev
      - POSTGRES_PASSWORD=strongpassword
      - POSTGRES_DB=chatlite_db
    ports:
      - "5432:5432"

volumes:
  postgres_data:
  static_volume: